### ISSUE TITLE
@DEFAULT-FROM-PREVIOUS-EVENT does not work with single quotes

### ISSUE THREAD

**Issue by pbchase** [ctsit/auto_populate_fields#11]
The @DEFAULT-FROM-PREVIOUS-EVENT action tag does not work with single quotes.  Double quotes work fine, but single quotes do not. In my test this field annotation content

`
@DEFAULT-FROM-PREVIOUS-EVENT_1='initial_dose'
@DEFAULT-FROM-PREVIOUS-EVENT_2='final_dose'
`

Resulted in the previous value for `final_dose` being used.

**Comment by vkuljak** [comment]
Does it work now with a single quote? Thanks.
