### ISSUE TITLE
Enabling the module throws an error

### ISSUE THREAD

**Issue by steentje34** [ctsit/auto_populate_fields#19]
Upon enabling the module, an error is thrown:
`DB Error: ALTER command denied to user 'redcap_user'@'vbimrct.internal.uzgent.be' for table 'redcap_log_event'`

This is obviously linked to this line of code:
https://github.com/ctsit/auto_populate_fields/blob/5282f6b8dff3458c2295a6275b53c974a20f3098/ExternalModule.php#L53

However, the standard REDCap database user only has SELECT, INSERT, UPDATE & DELETE rights. Could this be either solved or documented?

**Comment by pbchase** [comment]
@ChemiKyle, this is a small one we should take care of.  Could you document the requirement for the REDCap user to have alter-table privileges? 

If you want to take this to a higher level, you might be able to check the user rights at module enable time before trying to alter the table.  You might also be able to catch the error and provide some informational feedback. But first, document the requirement for alter-table privileges.

**Comment by marlycormar** [comment]
PR #22 documents the requirement for the REDCap user that enables the module to have alter-table privileges.
