### ISSUE TITLE
Default Values Not Displayed in Survey Mode

### ISSUE THREAD

**Issue by velezf** [ctsit/auto_populate_fields#20]
This module changes the default branching logic behavior as desired (allows defaults with branching logic) when using this module in the Add/Edit Records data entry workflow. 

However, it does not appear to work with the Survey workflow flow. It would be great if this same functionality existed for surveys.

**Comment by pbchase** [comment]
It's hard to say whether this is an enhancement or a bug. It seems like a good idea either way.

**Comment by marlycormar** [comment]
Issue fixed by PR #23.
