### ISSUE TITLE
New ver. 2.4.0 throws an error

### ISSUE THREAD

**Issue by JN71** [ctsit/auto_populate_fields#26]
We updated the auto-populate ti ver. 2.4.0 on the test server (REDCap 9.0.3), but get an PHP error (see pic). Ver. 2.3.0 runs fine.
![PHP error Auto_populate_fields v  2 4 0](https://user-images.githubusercontent.com/17781685/68459577-109ceb00-0206-11ea-9f0a-eedb85d5353d.jpg)
.

**Comment by jasonlones** [comment]
This happened at our site also.  After some digging, I found that when using @DEFAULT to a validated M-D-Y date field when the @DEFAULT value was Y-M-D (e.g. @DEFAULT='2019-06-29') the crash would occur.  Other combinations don’t seem to have an issue, but rather the defaulted date is put in the box regardless of the validation and eventually fails (if there is a mismatch) during save.

**Comment by JN71** [comment]
It also fails, when a Y-M-D date (e.g. '2019-06-29') is Default_0 in a D-M-Y-validated field and when a Y-M-D date is Default_0 in a Y-M-DY-validated field.

**Comment by pbchase** [comment]
@ChemiKyle, could you take a look at this? Perhaps PR #21 was not as shiny as we thought.

**Comment by ChemiKyle** [comment]
I only tested autopopulating using identical datetypes to correct a validation error. I had imagined that nobody would be mixing date formats in a single project, clearly a false assumption!

**Comment by pbchase** [comment]
@jasonlones, @JN71, Do you have a use case that requires mixing date formats in one project. i.e. do you _need_ two or more of YMD, DMY, and MDY? We would ordinarily advise our project builders to not do this. It risks confusion for people doing and reviewing the data entry. Also, realize that no matter the date format used, REDCap stores the value as the unambiguous, YYYY-MM-DD. 

Our preference is to _not_ support the mixing of different date formats, i.e. YMD vs DMY vs MDY. We can implement a change to prevent the crash and it happens to fix your _specific_ complaint but to do more than that is a good bit more work.

**Comment by jasonlones** [comment]
Philip,

I concur that there is not a good use case and, like you, we would normally recommending users avoid mixing formats.  However, the bigger issue in this case was that when the user (an admin) tested the project and inadvertently/unintentionally mixed the formats, the entire module crashed and became ‘unenabled’.  This shut off the module system-wide.  While there would be no use case to mix formats, there certainly is the off occasion where accidents occur and in those cases, it is quick a problem to have the entire module fail.

Thanks!

Jason Lones
IT Analyst, Sr.
Duke Office of Clinical Research (DOCR)
School of Medicine
Phone: (919) 668-1787

Need REDCap help?  Check out remote office hours every Thursday at 2p ET: via WebEx<https://dukemed.webex.com/dukemed/j.php?MTID=m80cefa3357146919ec3fbb4e15cd9ac8>.

**Comment by pbchase** [comment]
@jasonlones, I think we're on the same page. We'll fix the crash.

**Comment by jasonlones** [comment]
Thanks, Philip!  Your team is great!  Thanks for all you do!

Jason Lones
IT Analyst, Sr.
Duke Office of Clinical Research (DOCR)
School of Medicine
Phone: (919) 668-1787

Need REDCap help?  Check out remote office hours every Thursday at 2p ET: via WebEx<https://dukemed.webex.com/dukemed/j.php?MTID=m80cefa3357146919ec3fbb4e15cd9ac8>.

**Comment by JN71** [comment]
Hi @jasonlones & others - We are not mixing date formats in our projects - only using D-M-Y (or D-M-Y H:M for precision). I checked 4 different projects from A-Z. What I meant was that the database is Y-M-D natively and has to be formatted, when you use D-M-Y in your project.

But something strange happened this morning. Our REDCap page was blank white, because a nightly batch job had overridden our PHP 7 with a version 5. And all our doctors were complaining on the phone for an hour. But after our server admin reinstalled PHP 7, the site not only worked again, but this consistent PHP-error with auto-populate seems to be gone. Before it was everywhere, now I can´t replicate it.

I will test again and follow it through. Will let you know if it happens again

Best regards
Jeppe Neimann

**Comment by pbchase** [comment]
addressed by PR #27
