### ISSUE TITLE
default_when_visible.js does not wait for required core JS libs to load

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/auto_populate_fields#32]
Loading a form page results in a console error `ReferenceError: evalLogic is not defined` due to `autoPopulateFields.defaultWhenVisible.init` being called before REDCap core's JS libraries have loaded. https://github.com/ctsit/auto_populate_fields/blob/46df577507601e7a5fbcd6bc7bd86e06fddcec76/js/default_when_visible.js#L34.

Moving the function call under the `$(document).ready` block allows the library to load, however, it defeats the purpose of the function as the following alert now appears:  
![image](https://user-images.githubusercontent.com/20332546/70253316-fbf23b00-1750-11ea-8a00-341fbddca71d.png)

# Caveats
This error appears in REDCap 9.4.1, using Docker, on a very small project.

Due to the async nature of JS, it's possible that running this init function in `$(document).ready` will affect performance. ~~A better solution may be to force the JS file containing `evalLogic` (`/Resources/js/DataEntrySurveyCommon.js`) to load on the backend, but this is not as simple as adding `$this->includeJs(APP_PATH_WEBROOT . 'Resources/js/DataEntrySurveyCommon.js');` in `ExternalModule.php`~~. Forcing the dependency to load before `default_when_visible` does suppress the warning alert, but does **not** hide a branching logic field on page load if the field it checks is empty. In the example below, **choice_2** should only appear if **choice_1** is Yes.
![image](https://user-images.githubusercontent.com/20332546/70257073-abcaa700-1757-11ea-8ba5-6b61c195a9fb.png)

**Comment by ChemiKyle** [comment]
This issue first appears in REDCap 9.4.1, it also appears in 9.4.2 and 9.5.0 (latest at time of this comment).

**Comment by pbchase** [comment]
We have offers of testing assistance from felipe.cardoso@einstein.br and Sampson_Abiola@URMC.Rochester.edu

**Comment by pbchase** [comment]
@ChemiKyle, the record-cache issue we were discussing is at https://community.projectredcap.org/questions/74013/potential-issue-with-recordlist-and-shibboleth.html

**Comment by pbchase** [comment]
Addressed as PR #41
