### ISSUE TITLE
Max REDCap Version - 9.4.x (LTS is 9.5.x)

### ISSUE THREAD

**Issue by jasonlones** [ctsit/auto_populate_fields#39]
Friends, any chance you could bump the maximum required version this module?

Thanks!

**Comment by ChemiKyle** [comment]
Hi @jasonlones,

Unfortunately issue #32 prevents this; it will have to be addressed and tested before we can bump the max version of REDCap.

**Comment by jasonlones** [comment]
Okay, @ChemiKyle.  Thanks!  We'll wait.
