### ISSUE TITLE
Work on Survey?

### ISSUE THREAD

**Issue by johnliman** [ctsit/auto_populate_fields#40]
Hi @pbchase,

Thank you for the great EM, I am loving it, but could it be enabled for Survey as well?

Just for your consideration.

John

**Comment by johnliman** [comment]
Sample project for survey:

[AutoPopulateTest_2020-03-20_1350.REDCap.xml.zip](https://github.com/ctsit/auto_populate_fields/files/4357606/AutoPopulateTest_2020-03-20_1350.REDCap.xml.zip)

**Comment by ChemiKyle** [comment]
In the survey context, the data in `$Proj->metadata` does not actually apply the `class="@DEFAULT"` to the survey elements in the DOM. I think I should be able to add this and make it toggleable whether or not APF will apply to surveys.

**Comment by pbchase** [comment]
Addressed by PR #50
