### ISSUE TITLE
'Enable chronological previous event detection' fails

### ISSUE THREAD

**Issue by pbchase** [ctsit/auto_populate_fields#42]
The module configuration parameter 'Enable chronological previous event detection' fails in APF 2.5.0. I witnessed failures in 9.3.5 and 9.7.0. I saw failures in 9.3.5 in both a dev environment and production. 

When this option fails, the module provide no previous value at all. It does this quietly. if you turn off the option, you will get a value based on redcap event order sequencing.

**Comment by ChemiKyle** [comment]
Interesting, perhaps the balkanization of `redcap_event_log` has something to do with this.

**Comment by pbchase** [comment]
Addressed as PR #41
