### ISSUE TITLE
Module incompatible with REDCap > 9.4.0

### ISSUE THREAD

**Issue by mamanambiya** [ctsit/auto_populate_fields#43]
Getting this message when trying to install it on the version > 9.4.0. `Your REDCap version (9.5.13) is not compatible with this module. REDCap 9.4.0 is the maximum version that can be used with this module.`

**Comment by mamanambiya** [comment]
I see there a similar issue already (Issue #39). Any progress?

**Comment by ChemiKyle** [comment]
Hi @mamanambiya,

I solved the underlying problem in PR #41, but we found that problems appear again in >= 9.8.0. I am now working on integrating support for that.  
What version of REDCap are you targeting?

**Comment by ChemiKyle** [comment]
I am going to close this issue; we should be able to make a release once my PR is reviewed.

**Comment by mamanambiya** [comment]
Hi @ChemiKyle,
It was on version 9.5.13. We had upgraded to a more recent version. I have not seen yet seen the error message since the upgrade. We are probably not using version  9.8.0.

**Comment by ChemiKyle** [comment]
@mamanambiya something concerns me, you got this error message:  
`Your REDCap version (9.5.13) is not compatible with this module. REDCap 9.4.0 is the maximum version that can be used with this module.`

I wanted to remove the version limitation, but we did not set a maximum version number for this module in `config.json`!

**Comment by pbchase** [comment]
Addressed as PR #41
