### ISSUE TITLE
auto_populate_fields' module threw an exception under PHP8

### ISSUE THREAD

**Issue by pbchase** [ctsit/auto_populate_fields#61]
This error appeared after we upgraded to PHP8:

> The 'auto_populate_fields' module threw the following exception when calling the hook method 'redcap_every_page_top':
> 
> TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www.backup/redcap-20240819T2043/modules/auto_populate_fields_v2.6.0/ExternalModule.php:167
> Stack trace:
> #0 /var/www.backup/redcap-20240819T2043/modules/auto_populate_fields_v2.6.0/ExternalModule.php(167): in_array()
> #1 /var/www.backup/redcap-20240819T2043/modules/auto_populate_fields_v2.6.0/ExternalModule.php(36): AutoPopulateFields\ExternalModule\ExternalModule->setDefaultValues()
> #2 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/ExternalModules/classes/ExternalModules.php(3156): AutoPopulateFields\ExternalModule\ExternalModule->redcap_every_page_top()
> #3 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/ExternalModules/classes/ExternalModules.php(3323): ExternalModules\ExternalModules::startHook()
> #4 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/ExternalModules/classes/ExternalModules.php(3356): ExternalModules\ExternalModules::ExternalModules\{closure}()
> #5 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Classes/Hooks.php(41): ExternalModules\ExternalModules::callHook()
> #6 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Classes/HtmlPage.php(151): Hooks::call()
> #7 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Views/HeaderProject.php(46): HtmlPage->PrintHeader()
> #8 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/ProjectGeneral/header.php(4): require('...')
> #9 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/DataEntry/index.php(526): include('...')
> #10 {main}
> 
> URL: https://redcap.ctsi.ufl.edu/redcap/redcap_v14.6.2/DataEntry/index.php?pid=9941&id=197&event_id=95960&page=participant_and_study_partner_contact_information
> Server: redcap.ctsi.ufl.edu (redcap.ctsi.ufl.edu)
> User: XXXXXXX
> Project ID: 9941
> Module Name: Auto Populate Fields (auto_populate_fields)
> Module Author(s): XXXXXXXXXX
> Run Time: 0 seconds

**Comment by ChrWelker** [comment]
Sehr geehrte Damen und Herren, 

vielen Dank für Ihre Nachricht. Ich befinde mich derzeit nicht an meinem Arbeitsplatz und habe keinen regelmäßigen Zugriff auf meine E-Mails. Ihre E-Mail wird nicht weitergeleitet. Ab dem 26.08.2024 werde ich Ihr Anliegen gerne bearbeiten.

Mit freundlichen Grüßen
Christine Welker
___________________________________

Dr. Christine Welker
UR - Universität Regensburg
Institut für Epidemiologie und Präventivmedizin
Universitätsklinikum Regensburg
Franz-Josef-Strauß-Allee 11
D-93053 Regensburg
Telefon +49 941 944-5251
Fax +49 941 944-5202
***@***.***
www.uni-regensburg.de/epidemiologie

**Comment by pbchase** [comment]
@tlstoffs I have 3 such errors already today. I suspect this is a PHP8 compatibility issues we missed in testing

**Comment by pbchase** [comment]
Addressed by PR #62
