### ISSUE TITLE
@DEFAULT-WHEN-VISIBLE and @DEFAULT-FROM-PREVIOUS-EVENT behave oddly when used together.

### ISSUE THREAD

**Issue by rajputd** [ctsit/auto_populate_fields#8]
NOTE: DWV = @DEFAULT-WHEN-VISIBLE, DFPE = @DEFAULT-FROM-PREVIOUS-EVENT
 
When DFPE and DWV are used together on a hidden form field then DWV's value is what gets written into the form when it is made visible. However when DFPE and DWV are used on a visible form field then no default value is written into that field. This may be occurring because DWV does not set the default value of fields that are already visible. Or it might be a more complex issue.  Here are some steps to recreate this:

1. Create a select field inside an instrument that is repeated over multiple events.
2. Add a DFPE tag to that select field.
3. Create new record and fill out the first occurrence of that instrument for the record.
4. If you go to the next occurrence of the instrument DFPE should be working properly. 
5. Add a DWV tag alongside the DFPE tag.
6. If you refresh the next occurrence of the instrument you should see that no default value has been written to the form field that has both tags.

When DFPE's source field is set to a hidden field that uses DWV similar behavior occurs. When the DWV field in the previous event is visible DFPE works as expected. If the DWV field is not visible then DFPE stops working and no default value is set. Here are some steps to recreate this: 

1. Create one yes/no field and two select field inside an instrument that is repeated over multiple events.
2. Add branching logic to the first select field so that it is hidden depending on what value the yes/no field is set to.
3. Add a DWV tag to that first select field and a DFPE tag to the second select field. Set the source of the DFPE tag to be the first select field.
4. Create a new record. Fill out the first occurrence of the instrument. Make sure the first select field is not hidden by branching logic..
5. In the next occurrence of the instrument you should see DWV and DFPE working together properly.
6. Go back to the first occurrence of the instrument and hide the first select field via branching logic. If you go back to the second occurrence of the instrument you should see that no default value has been written into the second select field.

Although the following is not related to DWV and DFPE's interactions with one another it may be helpful when diagnosing the problem. If DFPE is used on a field hidden by branching logic then it triggers warnings within REDCap. When you enter a new form it will ask if you would like to erase the data for the field DFPE has been applied to. If cancel is selected the branching logic breaks and the hidden field becomes visible. It also holds whatever value DFPE assigns to it. If ok is selected then the branching logic remains intact but when the field is made visible it contains no default value.

**Comment by pbchase** [comment]
This is addressed in PR #9
